package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Adjustsalary;
import cn.sichu.vhr.web.mbg.model.AdjustsalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdjustsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Adjustsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Adjustsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Adjustsalary> selectByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Adjustsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Adjustsalary row, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Adjustsalary row, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Adjustsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Adjustsalary row);
}