package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Employeeec;
import cn.sichu.vhr.web.mbg.model.EmployeeecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(EmployeeecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(EmployeeecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Employeeec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Employeeec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Employeeec> selectByExample(EmployeeecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Employeeec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Employeeec row, @Param("example") EmployeeecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Employeeec row, @Param("example") EmployeeecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Employeeec row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Employeeec row);
}