package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Employeetrain;
import cn.sichu.vhr.web.mbg.model.EmployeetrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeetrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Employeetrain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Employeetrain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Employeetrain> selectByExample(EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Employeetrain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Employeetrain row, @Param("example") EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Employeetrain row, @Param("example") EmployeetrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Employeetrain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Employeetrain row);
}