package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Employeeremove;
import cn.sichu.vhr.web.mbg.model.EmployeeremoveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeremoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Employeeremove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Employeeremove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Employeeremove> selectByExample(EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Employeeremove selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Employeeremove row, @Param("example") EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Employeeremove row, @Param("example") EmployeeremoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Employeeremove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Employeeremove row);
}