package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Empsalary;
import cn.sichu.vhr.web.mbg.model.EmpsalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Empsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Empsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Empsalary> selectByExample(EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Empsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Empsalary row, @Param("example") EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Empsalary row, @Param("example") EmpsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Empsalary row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Empsalary row);
}