package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Hr;
import cn.sichu.vhr.web.mbg.model.HrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Hr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Hr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Hr> selectByExample(HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Hr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Hr row, @Param("example") HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Hr row, @Param("example") HrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Hr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Hr row);
}