package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.HrRole;
import cn.sichu.vhr.web.mbg.model.HrRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(HrRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(HrRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<HrRole> selectByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    HrRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") HrRole row, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") HrRole row, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(HrRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(HrRole row);
}