package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.MenuRole;
import cn.sichu.vhr.web.mbg.model.MenuRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(MenuRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(MenuRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<MenuRole> selectByExample(MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    MenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") MenuRole row, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") MenuRole row, @Param("example") MenuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(MenuRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(MenuRole row);
}