package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Msgcontent;
import cn.sichu.vhr.web.mbg.model.MsgcontentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgcontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Msgcontent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Msgcontent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Msgcontent> selectByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Msgcontent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Msgcontent row, @Param("example") MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Msgcontent row, @Param("example") MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Msgcontent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Msgcontent row);
}