package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Oplog;
import cn.sichu.vhr.web.mbg.model.OplogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(OplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(OplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Oplog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Oplog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Oplog> selectByExample(OplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Oplog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Oplog row, @Param("example") OplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Oplog row, @Param("example") OplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Oplog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Oplog row);
}