package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Politicsstatus;
import cn.sichu.vhr.web.mbg.model.PoliticsstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoliticsstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Politicsstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Politicsstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Politicsstatus> selectByExample(PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Politicsstatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Politicsstatus row, @Param("example") PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Politicsstatus row, @Param("example") PoliticsstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Politicsstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Politicsstatus row);
}