package cn.sichu.vhr.web.mbg.mapper;

import cn.sichu.vhr.web.mbg.model.Sysmsg;
import cn.sichu.vhr.web.mbg.model.SysmsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    long countByExample(SysmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByExample(SysmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insert(Sysmsg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int insertSelective(Sysmsg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    List<Sysmsg> selectByExample(SysmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    Sysmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExampleSelective(@Param("row") Sysmsg row, @Param("example") SysmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByExample(@Param("row") Sysmsg row, @Param("example") SysmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKeySelective(Sysmsg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    int updateByPrimaryKey(Sysmsg row);
}