package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depPath
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String deppath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.isParent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean isparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.parentId
     *
     * @return the value of department.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.parentId
     *
     * @param parentid the value for department.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depPath
     *
     * @return the value of department.depPath
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getDeppath() {
        return deppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depPath
     *
     * @param deppath the value for department.depPath
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setDeppath(String deppath) {
        this.deppath = deppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.enabled
     *
     * @return the value of department.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.enabled
     *
     * @param enabled the value for department.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.isParent
     *
     * @return the value of department.isParent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getIsparent() {
        return isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.isParent
     *
     * @param isparent the value for department.isParent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setIsparent(Boolean isparent) {
        this.isparent = isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentid=").append(parentid);
        sb.append(", deppath=").append(deppath);
        sb.append(", enabled=").append(enabled);
        sb.append(", isparent=").append(isparent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}