package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Employeeremove implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.afterDepId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer afterdepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.afterJobId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer afterjobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.removeDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date removedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.reason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.id
     *
     * @return the value of employeeremove.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.id
     *
     * @param id the value for employeeremove.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.eid
     *
     * @return the value of employeeremove.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.eid
     *
     * @param eid the value for employeeremove.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.afterDepId
     *
     * @return the value of employeeremove.afterDepId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getAfterdepid() {
        return afterdepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.afterDepId
     *
     * @param afterdepid the value for employeeremove.afterDepId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAfterdepid(Integer afterdepid) {
        this.afterdepid = afterdepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.afterJobId
     *
     * @return the value of employeeremove.afterJobId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getAfterjobid() {
        return afterjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.afterJobId
     *
     * @param afterjobid the value for employeeremove.afterJobId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAfterjobid(Integer afterjobid) {
        this.afterjobid = afterjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.removeDate
     *
     * @return the value of employeeremove.removeDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getRemovedate() {
        return removedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.removeDate
     *
     * @param removedate the value for employeeremove.removeDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRemovedate(Date removedate) {
        this.removedate = removedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.reason
     *
     * @return the value of employeeremove.reason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.reason
     *
     * @param reason the value for employeeremove.reason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.remark
     *
     * @return the value of employeeremove.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.remark
     *
     * @param remark the value for employeeremove.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", afterdepid=").append(afterdepid);
        sb.append(", afterjobid=").append(afterjobid);
        sb.append(", removedate=").append(removedate);
        sb.append(", reason=").append(reason);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}