package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Employeeec implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date ecdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecReason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String ecreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecPoint
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer ecpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecType
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer ectype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.id
     *
     * @return the value of employeeec.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.id
     *
     * @param id the value for employeeec.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.eid
     *
     * @return the value of employeeec.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.eid
     *
     * @param eid the value for employeeec.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecDate
     *
     * @return the value of employeeec.ecDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getEcdate() {
        return ecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecDate
     *
     * @param ecdate the value for employeeec.ecDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEcdate(Date ecdate) {
        this.ecdate = ecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecReason
     *
     * @return the value of employeeec.ecReason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getEcreason() {
        return ecreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecReason
     *
     * @param ecreason the value for employeeec.ecReason
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEcreason(String ecreason) {
        this.ecreason = ecreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecPoint
     *
     * @return the value of employeeec.ecPoint
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getEcpoint() {
        return ecpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecPoint
     *
     * @param ecpoint the value for employeeec.ecPoint
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEcpoint(Integer ecpoint) {
        this.ecpoint = ecpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecType
     *
     * @return the value of employeeec.ecType
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getEctype() {
        return ectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecType
     *
     * @param ectype the value for employeeec.ecType
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEctype(Integer ectype) {
        this.ectype = ectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.remark
     *
     * @return the value of employeeec.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.remark
     *
     * @param remark the value for employeeec.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", ecdate=").append(ecdate);
        sb.append(", ecreason=").append(ecreason);
        sb.append(", ecpoint=").append(ecpoint);
        sb.append(", ectype=").append(ectype);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}