package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Employeetrain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetrain.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetrain.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetrain.trainDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date traindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetrain.trainContent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String traincontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeetrain.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetrain.id
     *
     * @return the value of employeetrain.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetrain.id
     *
     * @param id the value for employeetrain.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetrain.eid
     *
     * @return the value of employeetrain.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetrain.eid
     *
     * @param eid the value for employeetrain.eid
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetrain.trainDate
     *
     * @return the value of employeetrain.trainDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getTraindate() {
        return traindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetrain.trainDate
     *
     * @param traindate the value for employeetrain.trainDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTraindate(Date traindate) {
        this.traindate = traindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetrain.trainContent
     *
     * @return the value of employeetrain.trainContent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getTraincontent() {
        return traincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetrain.trainContent
     *
     * @param traincontent the value for employeetrain.trainContent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTraincontent(String traincontent) {
        this.traincontent = traincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeetrain.remark
     *
     * @return the value of employeetrain.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeetrain.remark
     *
     * @param remark the value for employeetrain.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", traindate=").append(traindate);
        sb.append(", traincontent=").append(traincontent);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}