package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Employee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.idCard
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.wedlock
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String wedlock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.nationId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer nationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.nativePlace
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.politicId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer politicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.departmentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.jobLevelId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer joblevelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.posId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer posid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.engageForm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String engageform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.tiptopDegree
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String tiptopdegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.specialty
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.school
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.beginDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.workState
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String workstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.workID
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String workid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.contractTerm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Double contractterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.conversionTime
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date conversiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.notWorkDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date notworkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.beginContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date begincontract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.endContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date endcontract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.workAge
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer workage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.idCard
     *
     * @return the value of employee.idCard
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.idCard
     *
     * @param idcard the value for employee.idCard
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.wedlock
     *
     * @return the value of employee.wedlock
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getWedlock() {
        return wedlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.wedlock
     *
     * @param wedlock the value for employee.wedlock
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setWedlock(String wedlock) {
        this.wedlock = wedlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.nationId
     *
     * @return the value of employee.nationId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getNationid() {
        return nationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.nationId
     *
     * @param nationid the value for employee.nationId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setNationid(Integer nationid) {
        this.nationid = nationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.nativePlace
     *
     * @return the value of employee.nativePlace
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.nativePlace
     *
     * @param nativeplace the value for employee.nativePlace
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.politicId
     *
     * @return the value of employee.politicId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getPoliticid() {
        return politicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.politicId
     *
     * @param politicid the value for employee.politicId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPoliticid(Integer politicid) {
        this.politicid = politicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.departmentId
     *
     * @return the value of employee.departmentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.departmentId
     *
     * @param departmentid the value for employee.departmentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.jobLevelId
     *
     * @return the value of employee.jobLevelId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getJoblevelid() {
        return joblevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.jobLevelId
     *
     * @param joblevelid the value for employee.jobLevelId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setJoblevelid(Integer joblevelid) {
        this.joblevelid = joblevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.posId
     *
     * @return the value of employee.posId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getPosid() {
        return posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.posId
     *
     * @param posid the value for employee.posId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPosid(Integer posid) {
        this.posid = posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.engageForm
     *
     * @return the value of employee.engageForm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getEngageform() {
        return engageform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.engageForm
     *
     * @param engageform the value for employee.engageForm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEngageform(String engageform) {
        this.engageform = engageform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.tiptopDegree
     *
     * @return the value of employee.tiptopDegree
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getTiptopdegree() {
        return tiptopdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.tiptopDegree
     *
     * @param tiptopdegree the value for employee.tiptopDegree
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTiptopdegree(String tiptopdegree) {
        this.tiptopdegree = tiptopdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.specialty
     *
     * @return the value of employee.specialty
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.specialty
     *
     * @param specialty the value for employee.specialty
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.school
     *
     * @return the value of employee.school
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.school
     *
     * @param school the value for employee.school
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.beginDate
     *
     * @return the value of employee.beginDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.beginDate
     *
     * @param begindate the value for employee.beginDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.workState
     *
     * @return the value of employee.workState
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getWorkstate() {
        return workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.workState
     *
     * @param workstate the value for employee.workState
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setWorkstate(String workstate) {
        this.workstate = workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.workID
     *
     * @return the value of employee.workID
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.workID
     *
     * @param workid the value for employee.workID
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setWorkid(String workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.contractTerm
     *
     * @return the value of employee.contractTerm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Double getContractterm() {
        return contractterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.contractTerm
     *
     * @param contractterm the value for employee.contractTerm
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setContractterm(Double contractterm) {
        this.contractterm = contractterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.conversionTime
     *
     * @return the value of employee.conversionTime
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getConversiontime() {
        return conversiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.conversionTime
     *
     * @param conversiontime the value for employee.conversionTime
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setConversiontime(Date conversiontime) {
        this.conversiontime = conversiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.notWorkDate
     *
     * @return the value of employee.notWorkDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getNotworkdate() {
        return notworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.notWorkDate
     *
     * @param notworkdate the value for employee.notWorkDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setNotworkdate(Date notworkdate) {
        this.notworkdate = notworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.beginContract
     *
     * @return the value of employee.beginContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getBegincontract() {
        return begincontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.beginContract
     *
     * @param begincontract the value for employee.beginContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setBegincontract(Date begincontract) {
        this.begincontract = begincontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.endContract
     *
     * @return the value of employee.endContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getEndcontract() {
        return endcontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.endContract
     *
     * @param endcontract the value for employee.endContract
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEndcontract(Date endcontract) {
        this.endcontract = endcontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.workAge
     *
     * @return the value of employee.workAge
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getWorkage() {
        return workage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.workAge
     *
     * @param workage the value for employee.workAge
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setWorkage(Integer workage) {
        this.workage = workage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", idcard=").append(idcard);
        sb.append(", wedlock=").append(wedlock);
        sb.append(", nationid=").append(nationid);
        sb.append(", nativeplace=").append(nativeplace);
        sb.append(", politicid=").append(politicid);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", departmentid=").append(departmentid);
        sb.append(", joblevelid=").append(joblevelid);
        sb.append(", posid=").append(posid);
        sb.append(", engageform=").append(engageform);
        sb.append(", tiptopdegree=").append(tiptopdegree);
        sb.append(", specialty=").append(specialty);
        sb.append(", school=").append(school);
        sb.append(", begindate=").append(begindate);
        sb.append(", workstate=").append(workstate);
        sb.append(", workid=").append(workid);
        sb.append(", contractterm=").append(contractterm);
        sb.append(", conversiontime=").append(conversiontime);
        sb.append(", notworkdate=").append(notworkdate);
        sb.append(", begincontract=").append(begincontract);
        sb.append(", endcontract=").append(endcontract);
        sb.append(", workage=").append(workage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}