package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;

public class Hr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.telephone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.username
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.password
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.userface
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String userface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.id
     *
     * @return the value of hr.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.id
     *
     * @param id the value for hr.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.name
     *
     * @return the value of hr.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.name
     *
     * @param name the value for hr.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.phone
     *
     * @return the value of hr.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.phone
     *
     * @param phone the value for hr.phone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.telephone
     *
     * @return the value of hr.telephone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.telephone
     *
     * @param telephone the value for hr.telephone
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.address
     *
     * @return the value of hr.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.address
     *
     * @param address the value for hr.address
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.enabled
     *
     * @return the value of hr.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.enabled
     *
     * @param enabled the value for hr.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.username
     *
     * @return the value of hr.username
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.username
     *
     * @param username the value for hr.username
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.password
     *
     * @return the value of hr.password
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.password
     *
     * @param password the value for hr.password
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.userface
     *
     * @return the value of hr.userface
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getUserface() {
        return userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.userface
     *
     * @param userface the value for hr.userface
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setUserface(String userface) {
        this.userface = userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr.remark
     *
     * @return the value of hr.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr.remark
     *
     * @param remark the value for hr.remark
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", telephone=").append(telephone);
        sb.append(", address=").append(address);
        sb.append(", enabled=").append(enabled);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", userface=").append(userface);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}