package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.iconCls
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String iconcls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.keepAlive
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean keepalive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.requireAuth
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean requireauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component
     *
     * @return the value of menu.component
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component
     *
     * @param component the value for menu.component
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.iconCls
     *
     * @return the value of menu.iconCls
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.iconCls
     *
     * @param iconcls the value for menu.iconCls
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.keepAlive
     *
     * @return the value of menu.keepAlive
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getKeepalive() {
        return keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.keepAlive
     *
     * @param keepalive the value for menu.keepAlive
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setKeepalive(Boolean keepalive) {
        this.keepalive = keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.requireAuth
     *
     * @return the value of menu.requireAuth
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getRequireauth() {
        return requireauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.requireAuth
     *
     * @param requireauth the value for menu.requireAuth
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setRequireauth(Boolean requireauth) {
        this.requireauth = requireauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parentId
     *
     * @return the value of menu.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parentId
     *
     * @param parentid the value for menu.parentId
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.enabled
     *
     * @return the value of menu.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.enabled
     *
     * @param enabled the value for menu.enabled
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append(", path=").append(path);
        sb.append(", component=").append(component);
        sb.append(", name=").append(name);
        sb.append(", iconcls=").append(iconcls);
        sb.append(", keepalive=").append(keepalive);
        sb.append(", requireauth=").append(requireauth);
        sb.append(", parentid=").append(parentid);
        sb.append(", enabled=").append(enabled);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}