package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Msgcontent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcontent.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcontent.title
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcontent.message
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgcontent.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcontent.id
     *
     * @return the value of msgcontent.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcontent.id
     *
     * @param id the value for msgcontent.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcontent.title
     *
     * @return the value of msgcontent.title
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcontent.title
     *
     * @param title the value for msgcontent.title
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcontent.message
     *
     * @return the value of msgcontent.message
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcontent.message
     *
     * @param message the value for msgcontent.message
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgcontent.createDate
     *
     * @return the value of msgcontent.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgcontent.createDate
     *
     * @param createdate the value for msgcontent.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", message=").append(message);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}