package cn.sichu.vhr.web.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Salary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.basicSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer basicsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.bonus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.lunchSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer lunchsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.trafficSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer trafficsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.allSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer allsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.pensionBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer pensionbase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.pensionPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Float pensionper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.medicalBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer medicalbase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.medicalPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Float medicalper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.accumulationFundBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Integer accumulationfundbase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.accumulationFundPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private Float accumulationfundper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.id
     *
     * @return the value of salary.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.id
     *
     * @param id the value for salary.id
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.basicSalary
     *
     * @return the value of salary.basicSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.basicSalary
     *
     * @param basicsalary the value for salary.basicSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.bonus
     *
     * @return the value of salary.bonus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.bonus
     *
     * @param bonus the value for salary.bonus
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.lunchSalary
     *
     * @return the value of salary.lunchSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getLunchsalary() {
        return lunchsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.lunchSalary
     *
     * @param lunchsalary the value for salary.lunchSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setLunchsalary(Integer lunchsalary) {
        this.lunchsalary = lunchsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.trafficSalary
     *
     * @return the value of salary.trafficSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getTrafficsalary() {
        return trafficsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.trafficSalary
     *
     * @param trafficsalary the value for salary.trafficSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setTrafficsalary(Integer trafficsalary) {
        this.trafficsalary = trafficsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.allSalary
     *
     * @return the value of salary.allSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getAllsalary() {
        return allsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.allSalary
     *
     * @param allsalary the value for salary.allSalary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAllsalary(Integer allsalary) {
        this.allsalary = allsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.pensionBase
     *
     * @return the value of salary.pensionBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getPensionbase() {
        return pensionbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.pensionBase
     *
     * @param pensionbase the value for salary.pensionBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPensionbase(Integer pensionbase) {
        this.pensionbase = pensionbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.pensionPer
     *
     * @return the value of salary.pensionPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Float getPensionper() {
        return pensionper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.pensionPer
     *
     * @param pensionper the value for salary.pensionPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setPensionper(Float pensionper) {
        this.pensionper = pensionper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.createDate
     *
     * @return the value of salary.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.createDate
     *
     * @param createdate the value for salary.createDate
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.medicalBase
     *
     * @return the value of salary.medicalBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getMedicalbase() {
        return medicalbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.medicalBase
     *
     * @param medicalbase the value for salary.medicalBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setMedicalbase(Integer medicalbase) {
        this.medicalbase = medicalbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.medicalPer
     *
     * @return the value of salary.medicalPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Float getMedicalper() {
        return medicalper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.medicalPer
     *
     * @param medicalper the value for salary.medicalPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setMedicalper(Float medicalper) {
        this.medicalper = medicalper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.accumulationFundBase
     *
     * @return the value of salary.accumulationFundBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Integer getAccumulationfundbase() {
        return accumulationfundbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.accumulationFundBase
     *
     * @param accumulationfundbase the value for salary.accumulationFundBase
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAccumulationfundbase(Integer accumulationfundbase) {
        this.accumulationfundbase = accumulationfundbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.accumulationFundPer
     *
     * @return the value of salary.accumulationFundPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public Float getAccumulationfundper() {
        return accumulationfundper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.accumulationFundPer
     *
     * @param accumulationfundper the value for salary.accumulationFundPer
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setAccumulationfundper(Float accumulationfundper) {
        this.accumulationfundper = accumulationfundper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.name
     *
     * @return the value of salary.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.name
     *
     * @param name the value for salary.name
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary
     *
     * @mbg.generated Wed May 11 10:46:51 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", basicsalary=").append(basicsalary);
        sb.append(", bonus=").append(bonus);
        sb.append(", lunchsalary=").append(lunchsalary);
        sb.append(", trafficsalary=").append(trafficsalary);
        sb.append(", allsalary=").append(allsalary);
        sb.append(", pensionbase=").append(pensionbase);
        sb.append(", pensionper=").append(pensionper);
        sb.append(", createdate=").append(createdate);
        sb.append(", medicalbase=").append(medicalbase);
        sb.append(", medicalper=").append(medicalper);
        sb.append(", accumulationfundbase=").append(accumulationfundbase);
        sb.append(", accumulationfundper=").append(accumulationfundper);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}